using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.Roadmap;

[GenerateTypedNameReferences]
public sealed partial class RoadmapWindow : DefaultWindow
{
    public RoadmapWindow()
    {
        RobustXamlLoader.Load(this);
        var year = DateTime.UtcNow.Year;
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("fec-roadmap-rmc-header", ("year", year))); // FEC14
        Header.SetMessage(msg);
    }
}
