using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FEC14.JobWhitelist;

[GenerateTypedNameReferences]
public sealed partial class FECJobWhitelistWindow : DefaultWindow
{
    public FECJobWhitelistWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
