using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FEC14.Weather;

[GenerateTypedNameReferences]
public sealed partial class FECWeatherWindow : DefaultWindow
{
    public FECWeatherWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
