using Content.Client._FEC14.UserInterface; // FEC14
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Xenonids.JoinXeno;

[GenerateTypedNameReferences]
public sealed partial class LarvaQueueOfferWindow : DefaultWindow, IIgnoreCloseRecentWindow // FEC14
{
    public LarvaQueueOfferWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
