using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FEC14.Roadmap;

[GenerateTypedNameReferences]
public sealed partial class FECRoadmapChooserWindow : DefaultWindow
{
    public FECRoadmapChooserWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
