using System.Linq;
using Content.Client._RMC14.Roadmap;
using Content.Shared._FEC14.Roadmap;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._FEC14.Roadmap;

[GenerateTypedNameReferences]
public sealed partial class FECRoadmapWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;

    public FECRoadmapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("fec-roadmap-header", ("year", DateTime.UtcNow.Year)));
        Header.SetMessage(msg);

        var sections = _prototypes.EnumeratePrototypes<FECRoadmapSectionPrototype>()
            .OrderBy(s => s.Order)
            .ThenBy(s => s.ID);

        foreach (var section in sections)
        {
            var column = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 20, 0),
            };

            column.AddChild(new RoadmapVersionHeader { Text = Loc.GetString(section.Name) });

            foreach (var entry in section.Items)
            {
                column.AddChild(new RoadmapItem
                {
                    ItemState = entry.State switch
                    {
                        FECRoadmapState.InProgress => RoadmapItemState.InProgress,
                        FECRoadmapState.Partial => RoadmapItemState.Partial,
                        FECRoadmapState.Complete => RoadmapItemState.Complete,
                        _ => RoadmapItemState.Planned,
                    },
                    HeaderText = Loc.GetString(entry.Name),
                    Text = entry.Text is { } text ? Loc.GetString(text) : null,
                });
            }

            Columns.AddChild(column);
        }
    }
}
